export const ERRORS = {
  USER_NOT_AUTHORIZED: 'Пользователь не авторизован',
  INVALID_TOKEN: 'Неверный токен',
  INVALID_REQUEST_BODY: 'Неверное тело запроса',
  USER_ALREADY_EXISTS: 'Пользователь уже существует',
  INCORRECT_LOGIN_OR_PASSWORD: 'Неверный логин или пароль',
  USER_NOT_FOUND: 'Пользователь не найден',
  POST_NOT_FOUND: 'Пост не найден',
  COMMENT_NOT_FOUND: 'Комментарий не найден',
  LIKE_NOT_FOUND: 'Лайк не найден',
  SUBSCRIPTION_NOT_FOUND: 'Подписка не найдена',
  NOT_ENOUGH_RIGHTS: 'Недостаточно прав',
  EMAIL_ALREADY_IN_USE: 'Электронная почта уже используется',
  LIKE_ALREADY_EXISTS: 'Лайк уже существует',
  SUBSCRIPTION_ALREADY_EXISTS: 'Подписка уже существует',
  UNAVAILABLE_OPERATION: 'Недоступная операция',
  INTERVAL_SERVER_ERROR: 'Внутренняя ошибка сервера',
} as const;
