export const ERRORS = {
  USER_NOT_AUTHORIZED: 'User not authorized',
  INVALID_TOKEN: 'Invalid token',
  INVALID_REQUEST_BODY: 'Invalid request body',
  USER_ALREADY_EXISTS: 'User already exists',
  INCORRECT_LOGIN_OR_PASSWORD: 'Incorrect login or password',
  USER_NOT_FOUND: 'User not found',
  POST_NOT_FOUND: 'Post not found',
  COMMENT_NOT_FOUND: 'Comment not found',
  LIKE_NOT_FOUND: 'Like not found',
  SUBSCRIPTION_NOT_FOUND: 'Subscription not found',
  NOT_ENOUGH_RIGHTS: 'Not enough rights',
  EMAIL_ALREADY_IN_USE: 'Email already in use',
  LIKE_ALREADY_EXISTS: 'Like already exists',
  SUBSCRIPTION_ALREADY_EXISTS: 'Subscription already exists',
  UNAVAILABLE_OPERATION: 'Unavailable operation',
  INTERVAL_SERVER_ERROR: 'Internal server error',
} as const;
